# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(640, 480)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        Dialog.setFont(font)
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(115, 129, 255, 255), stop:0.505682 rgba(183, 140, 236, 255), stop:1 rgba(255, 133, 205, 255));")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 620, 80))
        font = QtGui.QFont()
        font.setFamily("DigItAl FingerpRINT PERSONAL US")
        font.setPointSize(20)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.passLabel = QtWidgets.QLabel(self.widget)
        self.passLabel.setGeometry(QtCore.QRect(20, 350, 600, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.passLabel.setFont(font)
        self.passLabel.setStyleSheet("background-color:none;\n"
"color:#fff;")
        self.passLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.passLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.passLabel.setLineWidth(1)
        self.passLabel.setMidLineWidth(0)
        self.passLabel.setText("")
        self.passLabel.setTextFormat(QtCore.Qt.RichText)
        self.passLabel.setScaledContents(True)
        self.passLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passLabel.setWordWrap(True)
        self.passLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.passLabel.setObjectName("passLabel")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(130, 160, 370, 30))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:none;\n"
"color:#fff;")
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(70, 200, 500, 80))
        self.frame.setStyleSheet("background-color:#fff;\n"
"border-radius:10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Generate = QtWidgets.QPushButton(self.frame)
        self.Generate.setGeometry(QtCore.QRect(400, 30, 80, 23))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setBold(False)
        font.setWeight(50)
        self.Generate.setFont(font)
        self.Generate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Generate.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(115, 129, 255, 255), stop:0.505682 rgba(183, 140, 236, 255), stop:1 rgba(255, 133, 205, 255));\n"
"color:#fff")
        self.Generate.setObjectName("Generate")
        self.PassLen = QtWidgets.QLineEdit(self.frame)
        self.PassLen.setGeometry(QtCore.QRect(20, 20, 360, 40))
        self.PassLen.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.PassLen.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.PassLen.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.PassLen.setStyleSheet("background-color: #fff;\n"
"border:1px solid #ddd;\n"
"border-radius:10px;")
        self.PassLen.setAlignment(QtCore.Qt.AlignCenter)
        self.PassLen.setPlaceholderText("")
        self.PassLen.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.PassLen.setClearButtonEnabled(True)
        self.PassLen.setObjectName("PassLen")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(-200, -200, 0, 0))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Random Password Generator"))
        self.label.setText(_translate("Dialog", "Random Password Generator"))
        self.label_3.setText(_translate("Dialog", "Enter Password Length"))
        self.Generate.setText(_translate("Dialog", "Generate"))
        self.Generate.setShortcut(_translate("Dialog", "Return"))
        self.pushButton.setShortcut(_translate("Dialog", "Esc"))
